[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "e0b5fccb9e28d23396e3fbfd6cfe1055053f3a5a"
os = "macos"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "9f9ad644db553875bdab8aa5e353ce1f14bbdde4f4251128b6a56f381a670ed1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+1/GAP_pkg_cddinterface.v202400.900.200.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "f84964529e06c681820a2ee16191f4978f8358d7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "036e36332fdc3a3caf8fc4d6c0e9c9889fe35265b0d4a0c4d64052e39d1cbbfc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+1/GAP_pkg_cddinterface.v202400.900.200.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "f868009c4b9922e6304d031a39d5e4163c8a56e8"
libc = "musl"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "774c4ba327f1d911999409b8a5e074827ccc444717058d9874450e4ee40ff43d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+1/GAP_pkg_cddinterface.v202400.900.200.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "powerpc64le"
git-tree-sha1 = "cd5c39f33af90d0b2b28eb3bc765a766c8b2939d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "64f376a19114cc9bf3f7492af6347f9cdb95b65378b3b1bf81da6910107b7c10"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+1/GAP_pkg_cddinterface.v202400.900.200.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "93aab63e728544d6c15f3849a67883725ed3134c"
os = "macos"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "eb7c6bcec86f0950dc72ae68696092a1176a77a36f161b4e9c478064a1a5d1a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+1/GAP_pkg_cddinterface.v202400.900.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "7899f66e082e69928aeb60412e94120c4017b39c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "4014bc0aac93300679af17494ca8a10ccdeb760d8decb8be665017c44912a859"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+1/GAP_pkg_cddinterface.v202400.900.200.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "9f0212659f48d85180c1df57bcc3e0df36a7c469"
libc = "musl"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "01217f07e8a53ad2f58cd3cc8b5bd376c2acb677c0f28077d8ff456cbfd9e45a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+1/GAP_pkg_cddinterface.v202400.900.200.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "115103ff154cb7d3897d5971d6d58ee538121d3d"
os = "freebsd"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "19270ff2df0118c8e62100756ce3c53fb0dba34644b0b34e79540beb35225433"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+1/GAP_pkg_cddinterface.v202400.900.200.x86_64-unknown-freebsd.tar.gz"
