[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "8403ecc9e44d754aa0241028e85634c479210f39"
os = "macos"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "c1aeaf1f89f446f7f5d3b6af192ce605a3cd6eeb773294cf93f072228e5a0411"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.203+0/GAP_pkg_cddinterface.v202400.900.203.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "253f7b77b281863f5a453bb7651a06afb7e11d94"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "68814fbeac33b0f5d6520221718feade5a2666afbc8cf4baa8974c47fd1ec1a8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.203+0/GAP_pkg_cddinterface.v202400.900.203.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "5d56e19da1baa34293c37d261804ea9758a3487a"
libc = "musl"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "b417c52461c9bffad7758cb7a1732290887863da3f67959afa639f36c0612081"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.203+0/GAP_pkg_cddinterface.v202400.900.203.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "3e930ccacf64b999ac114e35a22664ac1cb3341b"
os = "freebsd"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "ba02f6bf453ede447820b8bd580cc1496c9aca3f58f5e22cdc729cdf84378c0a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.203+0/GAP_pkg_cddinterface.v202400.900.203.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "powerpc64le"
git-tree-sha1 = "0555291e94fd5345396aac055f3a9bf79b4d794b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "01bc4a0e8b2f9c3db83d06e3d7e531b99ea39db37cfa9bc2d703159585215ba1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.203+0/GAP_pkg_cddinterface.v202400.900.203.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "riscv64"
git-tree-sha1 = "a65bd7eca6f60335d03a3b29e752462c5cfc5dd5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "cf095771f3c9d824741e7964b3470544d3bcd3a1de1c93f1f11cc9876c6f4124"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.203+0/GAP_pkg_cddinterface.v202400.900.203.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "7342932f8b474cba087c14dc7955a3423c5d31d6"
os = "macos"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "7dbf62a8c295f73b9938d1917810037fc368230ec523c7cbfdb0775cb62c573d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.203+0/GAP_pkg_cddinterface.v202400.900.203.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "a1e704f961feffb6d2c904f6ba8de76440ae5cff"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "c1ba0bbaf2a7089ecb7d1b31c42a6f5dabcb379631e83984efc3b44d280c8cae"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.203+0/GAP_pkg_cddinterface.v202400.900.203.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "5fcd0b630bbf1b20008e48f3c7b06099c111c11f"
libc = "musl"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "a255c3fd3b083d5eca5a6c8d9db64db8f79fca910b5ae342e2271fcee6b2bd6a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.203+0/GAP_pkg_cddinterface.v202400.900.203.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "177274e317daa2218bd0f20149077a397f530e5d"
os = "freebsd"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "9827e744505f7cb5a03873a0d2cddc8e71f1a3452893cbf9b126d2c1f5b9d979"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.203+0/GAP_pkg_cddinterface.v202400.900.203.x86_64-unknown-freebsd.tar.gz"
