[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "8403ecc9e44d754aa0241028e85634c479210f39"
os = "macos"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "c1aeaf1f89f446f7f5d3b6af192ce605a3cd6eeb773294cf93f072228e5a0411"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.202+0/GAP_pkg_cddinterface.v202400.900.202.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "f84964529e06c681820a2ee16191f4978f8358d7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "036e36332fdc3a3caf8fc4d6c0e9c9889fe35265b0d4a0c4d64052e39d1cbbfc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.202+0/GAP_pkg_cddinterface.v202400.900.202.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "f868009c4b9922e6304d031a39d5e4163c8a56e8"
libc = "musl"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "774c4ba327f1d911999409b8a5e074827ccc444717058d9874450e4ee40ff43d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.202+0/GAP_pkg_cddinterface.v202400.900.202.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "5b8abfe94b35242bfb51dbf88a8abed2f0f6e668"
os = "freebsd"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "6c1023ed7fe33c4092c9e7b8a8861a9d64bbbb67f7c672b44fb3c3ecb293ee11"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.202+0/GAP_pkg_cddinterface.v202400.900.202.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "powerpc64le"
git-tree-sha1 = "cd5c39f33af90d0b2b28eb3bc765a766c8b2939d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "64f376a19114cc9bf3f7492af6347f9cdb95b65378b3b1bf81da6910107b7c10"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.202+0/GAP_pkg_cddinterface.v202400.900.202.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "riscv64"
git-tree-sha1 = "b9a89305cfecb04241a9e43c45bff64b941b1f37"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "98bd9051ff7f126d1eac0f0bbb5b441d41e5ddfe628bfe76d1150a8b01b46b5e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.202+0/GAP_pkg_cddinterface.v202400.900.202.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "7342932f8b474cba087c14dc7955a3423c5d31d6"
os = "macos"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "7dbf62a8c295f73b9938d1917810037fc368230ec523c7cbfdb0775cb62c573d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.202+0/GAP_pkg_cddinterface.v202400.900.202.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "7899f66e082e69928aeb60412e94120c4017b39c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "4014bc0aac93300679af17494ca8a10ccdeb760d8decb8be665017c44912a859"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.202+0/GAP_pkg_cddinterface.v202400.900.202.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "9f0212659f48d85180c1df57bcc3e0df36a7c469"
libc = "musl"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "01217f07e8a53ad2f58cd3cc8b5bd376c2acb677c0f28077d8ff456cbfd9e45a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.202+0/GAP_pkg_cddinterface.v202400.900.202.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "3c5ef4c4bb8619b7fb252ccea6159fe44c48a067"
os = "freebsd"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "1702a46804a7a41921f7e7d8a9fd1de7c1561dabd3cba674eb62c411fa69e3ef"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.202+0/GAP_pkg_cddinterface.v202400.900.202.x86_64-unknown-freebsd.tar.gz"
