[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "de54bf67efbc3237c2f0ffd2d1b740bbe635d2f3"
os = "macos"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "4e328aec64af4c6511a0ed2bc4207e228cc6fcfd2a765a03b512962a3abb49e9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202200.1100.100+0/GAP_pkg_cddinterface.v202200.1100.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "7746effb32cb0704a8068644db7a0bce8d858d3d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "c40dda351fe6866e997dc24e74173b76f527024f945f1a0f3d35d1e6206ee680"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202200.1100.100+0/GAP_pkg_cddinterface.v202200.1100.100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "29e36cddd1baf61ddf1b9094b5c45f15176b515a"
libc = "musl"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "ca2cb401c93e3e2378f71817f47ad9f5b764c5938317cbd412ac6a95791efe1d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202200.1100.100+0/GAP_pkg_cddinterface.v202200.1100.100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "powerpc64le"
git-tree-sha1 = "c69c3d2a225d94bf2ef5ce4109716565e69d3331"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "5f3e235ddc67689c56b097de4b3439c2b69e30a828d034437734318f8adf20b7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202200.1100.100+0/GAP_pkg_cddinterface.v202200.1100.100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "15ddfd6432fc0162c2422e7fd0d73038aeaa00d1"
os = "macos"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "ce1beac98288f8b4b1d00ab929a6c636f9d7f13173539250bc5574905928a785"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202200.1100.100+0/GAP_pkg_cddinterface.v202200.1100.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "739be3cb1740125f7036d4be104a4b8e57b38d8d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "efe791faeb021f5854066eec0d47845f62480fc7b899a47cde41ab56a003ac3d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202200.1100.100+0/GAP_pkg_cddinterface.v202200.1100.100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "c0253127d794fafe62dc717eac7422009cb371d1"
libc = "musl"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "911a92006905f5a42c59c532d836ca93f05d5ff2a8c98ad4a301f6d7091a521c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202200.1100.100+0/GAP_pkg_cddinterface.v202200.1100.100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "be20d8f249527f674ccfd70da4cca1c94cc9a165"
os = "freebsd"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "50240fa9a0260c23b59d579001bd4435a397ceef8cd04d5d9221c1ff102dd673"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202200.1100.100+0/GAP_pkg_cddinterface.v202200.1100.100.x86_64-unknown-freebsd.tar.gz"
