[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "6df48332ace994dedd352de3ebfbf1840aae6ab0"
os = "macos"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "b8a07ad84bfe098986bf4d9a81a0a159742df0dcd6d23ec527473e251cfea381"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+0/GAP_pkg_cddinterface.v202400.900.200.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "b338a37e2fdea1843ad769fbbda9216ceea02ca2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "2bb55c642c661570ccc9a11bdf9c4b4ed697bbab58c6f6d62ddf6ede385b49eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+0/GAP_pkg_cddinterface.v202400.900.200.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "aarch64"
git-tree-sha1 = "774b256c6ca141dee4d35dfbdae338b3ebc50963"
libc = "musl"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "957cd260f28d3501fa93dad77ffe8268fc719f9cff32441b81bd432c6bd96a2f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+0/GAP_pkg_cddinterface.v202400.900.200.aarch64-linux-musl.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "powerpc64le"
git-tree-sha1 = "8829d6a3e980522e02937d421948ee6a55009e1f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "d243a691886f70a92005270146ccf4af752a18ed4fbf37444288afd37be686d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+0/GAP_pkg_cddinterface.v202400.900.200.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "3d0186aa75b9240187b57d6c6214dbbca829df28"
os = "macos"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "c97c79a9eb905efaaeb7f57f7458a4dd42766c641864f4b5796a1b1c3d02cff6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+0/GAP_pkg_cddinterface.v202400.900.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "f07c04d2c216d42075bd7e937dd7057af6d9c8f4"
libc = "glibc"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "2bcc2c1ef4cc973b75f3f998d01021cb39442550b560968721da021639203c4a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+0/GAP_pkg_cddinterface.v202400.900.200.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "8accf49659a77bb063042c046680350afe1a16f2"
libc = "musl"
os = "linux"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "61d00fcbc47a9826916e2121e1e8a9b6f460595783394ab6260ed583bab673c5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+0/GAP_pkg_cddinterface.v202400.900.200.x86_64-linux-musl.tar.gz"
[[GAP_pkg_cddinterface]]
arch = "x86_64"
git-tree-sha1 = "430892a3dc2a549989c2b8cab5e0055b93cc0f27"
os = "freebsd"

    [[GAP_pkg_cddinterface.download]]
    sha256 = "7fb0a124c50780203b121b92e2ed0024da7b3469fe97a85213549fe8151cf3a9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_cddinterface_jll.jl/releases/download/GAP_pkg_cddinterface-v202400.900.200+0/GAP_pkg_cddinterface.v202400.900.200.x86_64-unknown-freebsd.tar.gz"
